### ISSUE TITLE
Cant get example to run

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [GetStream/react-native-activity-feed#1]
Can someone create clear documentation on how to install and run the sample project. I tried to folow the readme but not getting any luck

$ npm i expo-activity-feed --save
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../expo-package

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/denzelgent/.npm/_logs/2018-08-31T14_39_14_962Z-debug.log

**Comment by tbarbugli** [comment]
@imanodaysoffdotcom this project is still going under heavy development and docs are not always in sync with the latest version of example or libs. 

Can you paste the exact list of commands that you are using to test the sample project?

I also suggest using `yarn` to run the example instead of `npm` and do something like this:

```bash
git clone git@github.com:GetStream/react-native-activity-feed.git
cd react-native-activity-feed
yarn
cd example
yarn
```
