### ISSUE TITLE
doFeedRequest does not work with NotificationFeed component

### ISSUE THREAD

**Issue by aderici** [GetStream/react-native-activity-feed#103]
**Setup (always fill this in):**

- iOS or Android?
iOS
- Expo or regular React Native?
Expo
- React Native Version:
- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
0.8.18
- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`
4.4.0
**Describe the bug**
I am using NotificationFeed component to display a feed page in my mobile app. I assumed that using doFeedRequest prop to provide an alternative function would a very simple and efficient way to do enrichment and still keep the official frontend components.

I have found this gist that demonstrates the usage successfully and it works : 

https://gist.github.com/siman/d0e035065fc4dd8738a2dcfcb39cd5e4

Unfortunately this is for FlatFeed component. And even though NotificationFeed provides the same prop, it is not able to carry it into the deeper components and props.doFeedRequest is null when i try to debug the inner mechanics of the components. I believe there is a bug with NotificationFeed that prevents it from using the custom doFeedRequest function

**To Reproduce**

Use NotificationFeed component, provide a custom function as doFeedRequest prop, unfortunately it is not used

**Expected behavior**
Component should use the custom function to make feed requests.

**Screenshots**
n/a
**Additional context**
n/a

**Comment by jaapbakker88** [comment]
@aderici We've looked into this and because of they way the library works your indeed right the doFeedRequest doesn't work on the NotificationFeed because we handle the options somewhere else. 

You can work around this by the following: 
```
<StreamApp
    sharedFeeds={[
        {
          feedGroup: 'notification',
          notify: true,
          options: {mark_seen: true},
          doFeedRequest: (session, feedGroup, feedId, options) => console.log(session, feedGroup, feedId, options),
        },
     ]}
>
```

Because the notification feed needs to be accessible in multiple locations we need to add it to the shared feeds. And the notification feed is the only one we do this to by default. Because people would likely want to show a counter in the navigation for instance. 

So the above is one option to achieve what you are doing. 

The other option is passing an empty array to `sharedFeeds` on `StreamApp` and then your code should work fine, but you only want to do this if you don't need to have access to the notification feed in the sharedFeeds manager.

**Comment by aderici** [comment]
hi thanks for the response, 

i am actually using the shared feeds because i want to display a badge icon on the navigation and the feed itself as you already mentioned.

I will try the suggested solution and get back with the results

Best regards,

**Comment by jaapbakker88** [comment]
Let me know if this resolves your issue.

**Comment by aderici** [comment]
Hi, thanks the proposed solution did resolve my issue as i can inject a custom function to make the feed request, so that i can call my backend to enrich feed data.
