### ISSUE TITLE
Need Multiline support

### ISSUE THREAD

**Issue by jamesawer3** [GetStream/react-native-activity-feed#81]
**Setup (always fill this in):**

- iOS or Android?
  Both
- Expo or regular React Native?
  React Native
- React Native Version:
  0.59.5
- `react-native-activity-feed` or `expo-activity-feed` version: `npm list --pattern <package-name>`/`yarn list --pattern <package-name>`
  react-native-activity-feed - ^0.8.16
- `getstream` version: `npm list --pattern getstream`/`yarn list --pattern getstream`
  getstream@4.2.5

**Describe the bug**
  If I enable multiline using textInput props in [commentBox](https://getstream.github.io/react-native-activity-feed/#commentbox) in iOS message is posted but textInput is not clearing after posting but in android I can't even post the comment.

**Comment by jamesawer3** [comment]
@jaapbakker88 Can you please help me with this

**Comment by jaapbakker88** [comment]
@jamesawer3 the problem is that when you enable multiline on the TextInput on android there is no submit button. Only a return button which includes a line break. On iOS it's a bug with React that should be solved once we upgrade to a newer version. That's going to take some time though and I don't know when we'll be able to get around to it. There is a hack for iOS but it's not a very satisfying solution as it doesn't help for Android. For now I suggest not using multiline until we upgrade to a newer version of React Native.

Some more information about android: https://stackoverflow.com/questions/37587865/multiline-text-input-with-a-done-submit-button-on-keyboard-on-android

And more information about the iOS bug:  https://github.com/facebook/react-native/issues/18874
